############################################################################
# file:			Makefile																
# authors:	Matúš Liščinský xlisci02								
#						Vladimír Marcin xmarci10									
############################################################################

all: blockeditor

blockeditor:
	qmake BlockEditor.pro
	$(MAKE) -f gui_makefile

clean:
	rm -f gui_makefile ../blockeditor moc* qrc* *.o
	


