#  Makefile
#  IPK 2018 - 2.Projekt 
#  Autor: Matus Liscinsky
#  Login: xlisci02
#  Mail: xlisci02@stud.fit.vutbr.cz
#  Datum: 9.4.2018
#  make - preklad
#  make clean - zmaze vytvorenu binarku

CC= gcc
CFLAGS= -Wall

all: ipk-dhcpstarve

ipk-dhcpstarve: ipk-dhcpstarve.c ipk-dhcpstarve.h
	$(CC) $(CFLAGS) ipk-dhcpstarve.c -o ipk-dhcpstarve

clean: 
	@rm ipk-dhcpstarve
