#FILE		Makefile
#Author		Matus Liscinsky
#Login		xlisci02
#Mail		xlisci02@stud.fit.vutbr.cz
#Date		12.05.2017

PROJ=proj5

all:
	pdflatex $(PROJ).tex

clean:
	rm -f $(PROJ).aux $(PROJ).log $(PROJ).nav $(PROJ).pdf $(PROJ).out $(PROJ).snm $(PROJ).toc
